### ISSUE TITLE
Final Render checklist

### ISSUE THREAD

**Issue by EmilHvitfeldt** [EmilHvitfeldt/smltar#93]
- [x] Use package installs from CRAN and GitHub only. No local
- [x] Make sure that `plot_text_explanations()` output is replaced with images
- [x] Make sure to re-lint all the code
- [ ] Make sure there are no odd page breaks
- [ ] Make sure to delete the parrot
- [ ] Make sure `tuning` folder is deleted
- [ ] Render with `bookdown::render_book("index.Rmd", "bookdown::pdf_book")`

**Comment by juliasilge** [comment]
Use `render_smltar.R` to check some of these

**Comment by juliasilge** [comment]
As of today, we still need GitHub versions of parsnip (maybe can get a CRAN release of that when Max gets back from vacation), pillar (for the non-ugly tibble list col printing), and scotus (which will not go to CRAN ever).

**Comment by EmilHvitfeldt** [comment]
With regard to soctus. Should I bump the version up and give it a github release? Just to signify that it is stable

**Comment by juliasilge** [comment]
I think that's a good idea, yes 👍

**Comment by juliasilge** [comment]
Book is in print! ✅
